### ISSUE TITLE
Error during Bootstrapping project for local development

### ISSUE THREAD

**Issue by ghost** [CiscoCloud/shipped-feedback#11] opened 2015-12-15 05:40 UTC
Trying to bootstrap into my windows machine .Getting following err:

PS C:\Users<user>> .\shipped.exe -t EkezMJUJKfWuuoZamojSjNisxUpuiqfQ -s https://api.ciscoshipped.io/ Local bootstrap
849aab48-a2e7-11e5-ab9d-0242ac11015e
# git 1.9.5 is installed.
# Cloning Repositories
# Looks like service 1 pythonservice15dec is already cloned - found .git directory in TestProject15Dec/pythonservice15dec
# Download Configuration

ERROR Bootstrap failed: No VM definitions in Vagrantfile

What can be the cause and its resolution?

**Comment by npateriya** [comment] 2015-12-15 06:14
Most likely your service is creation has error. 
Can you login to UI and go to project, it should should show error in service creation and option to repair service. Try to repair service. One service on UI have no error. 

Remove local project directory and rerun bootstrap command. 

I will open issue in cli so that it report more useful message. 

You can also join shipped-support room in Spark, for basic issue you can post message in spark support room too.

**Comment by ghost** [comment] 2015-12-15 07:18
![image](https://cloud.githubusercontent.com/assets/16284693/11804806/877d15a2-a32c-11e5-876f-11b3e1fe0438.png)

![image](https://cloud.githubusercontent.com/assets/16284693/11804441/d54e6fae-a329-11e5-9090-4858ea739e65.png)

I am trying to repair service but its not getting repaired.
I have just created a test project and added golang service in it.On starting build getting error as seen in the attached image.

Can you please let me know how can I add myself in ur cisco spark room or vice versa.

**Comment by mikeihbe** [comment] 2015-12-15 16:39
Do you have administration privileges for this repository in github?

On Tue, Dec 15, 2015 at 1:18 AM, RuchiCisco notifications@github.com
wrote:

> [image: image]
> https://cloud.githubusercontent.com/assets/16284693/11804441/d54e6fae-a329-11e5-9090-4858ea739e65.png
> 
> I am trying to repair service but its not getting repaired.
> I have just created a test project and added golang service in it.On
> starting build getting error as seen in the attached image.
> 
> Can you please let me know how can I add myself in ur cisco spark room or
> vice versa.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CiscoCloud/shipped-feedback/issues/11#issuecomment-164667499
> .

## 

Mike Ihbe
MustWin - Principal

mike@mustwin.com
mikejihbe@gmail.com
skype: mikeihbe
Cell: 651.283.0815

**Comment by npateriya** [comment] 2015-12-15 22:13
- How do I report an issue during the Shipped Beta Process?
  -  Sign-up for Cisco Spark using your corporate email by visiting https://web.ciscospark.com.
  -  Search or find the spark channel “shipped-support”.
  - Start reporting issues and asking questions in the “shipped-support” channel. Developers and experienced users will provide quick and interactive help .
- What information do I need to provide to Shipped scrum team  for debugging my issues ?
  - Shipped CLI  Bootstrap Failure Issue :  Please Share shipped-cli.log file, which is created in your current working directory from where cli was invoked. 
  - Shipped UI: Build, Deploy failures : Please add Shipped team member (who is helping out with the issue)  as collaborator. Steps is in the attached InviteCollaborators.pdf file.

**Comment by ghost** [comment] 2015-12-16 05:15
@mikeihbe : Yes I have admin rights. I only created this repository while adding buildpack for services from shipped UI.
@npateriya not able to find “shipped-support” in spark rooms search.Could you please add me in there..my id is rusharm2@cisco.com

**Comment by RuchiShCisco** [comment] 2015-12-18 05:17
Any way forward in this?

**Comment by npateriya** [comment] 2015-12-18 05:37
It seems like you deleted your complete github user account 'RuchiCisco' (now ghost) and recreated other with same name. That lead to multiple users entries with same identifier. This is edge case (not common scenario) and seems to be creating issue while registering service callback. I have opened  issue on our product to reproduce and investigate this scenario further. 
If possible I please try using alternate account name to unblock, we can try to manually cleanup database for duplicate enteries but that may take sometime.

**Comment by RuchiShCisco** [comment] 2015-12-18 05:42
thanks ..its working now :)

**Comment by RuchiShCisco** [comment] 2015-12-18 06:38
the project got repaired now after changing username of my github acc...now bootsrapping to local giving error "ERROR Bootstrap failed: Download of .drone.sec failed with error 500 Internal Server Error - Internal Server Error"

**Comment by RuchiShCisco** [comment] 2015-12-18 07:32
Shipped-cli.log : 
Starting download of https://api.ciscoshipped.io//cli/88345f50-a479-11e5-a6b7-0242ac1102a1/9c0c85db-a479-11e5-a6b8-0242ac1102a1/drone.sec?api_token=uAttpUJwkxXPNNwpqfmTcZSeENztppZo to FirstProject17Dec/firstgolang17dec/.drone.sec

TRACE 2015/12/18 12:58:51.004069 client.go:114: GET https://api.ciscoshipped.io/projects/88345f50-a479-11e5-a6b7-0242ac1102a1?api_token=uAttpUJwkxXPNNwpqfmTcZSeENztppZo
TRACE 2015/12/18 12:58:51.251618 client.go:159: Request status code 200 (200 OK)

TRACE 2015/12/18 12:58:51.254619 projects.go:304: Changed to project 88345f50-a479-11e5-a6b7-0242ac1102a1 directory C:\Users\rusharm2/FirstProject17Dec
ERROR 2015/12/18 12:58:51.255619 commands.go:98: Bootstrap failed: Download of .drone.sec failed with error 500 Internal Server Error - Internal Server Error

**Comment by RuchiShCisco** [comment] 2015-12-18 07:32
![image](https://cloud.githubusercontent.com/assets/16331226/11891764/9a7aa5c2-a587-11e5-8499-c35a7a933e56.png)

**Comment by RuchiShCisco** [comment] 2015-12-18 07:34
docker.yml :


image: golang:1.5
git:
  path: github.com/RuchiCisco/firstgolang17dec
script:
  - echo "build commands"
  - .shipped/build
  - .shipped/test
clone:
  path: github.com/RuchiCisco/firstgolang17dec
build:
  image: golang:1.5
  commands:
    - echo "build commands"
    - .shipped/build
    - .shipped/test
publish:
  docker:
    dockerfile: ./Dockerfile
    docker_host: 10.10.10.15:2375
    docker_version: 1.4.1
    registry_login_url: $$bintray_repo_login_url
    registry_login: true
    username: $$bintray_user
    password: $$bintray_api_key
    email: $$bintray_user_email
    image_name: $$bintray_image_name
    push_latest: true
    tag: $$COMMIT

    registry: $$bintray_registry
    repo: $$bintray_repo
notify:
  webhook:
    image: shippedrepos-docker-drone.bintray.io/drone-webhook
    urls:
      - "https://api.ciscoshipped.io/webhooks/drone"
    on_success: true
    on_failure: true

**Comment by npateriya** [comment] 2016-01-22 02:27
Closing as its working now.

**Closed as completed by npateriya** 2016-01-22 02:27 UTC
